### ISSUE TITLE
Compilation error: argument ‘_fmt’ might be clobbered by ‘longjmp’

### ISSUE THREAD

**Issue by BinyaminSharet** [wahern/hexdump#1]
I ran into compilation issue when compiling hexdump from git ( commit 
8b5a375c0d3491514637268b0c845c9a396afa86 )
os: ubuntu 14.04
compiler: gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

```
$ make -f Makefile hexdump
cc -std=c99 -g -O2 -Wall -Wextra -Werror -Wno-unused-variable -Wno-unused-parameter -o hexdump hexdump.c  -DHEXDUMP_MAIN
hexdump.c: In function ‘hxd_compile’:
hexdump.c:1338:48: error: argument ‘_fmt’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
 int hxd_compile(struct hexdump *X, const char *_fmt, int flags) {
                                                ^
cc1: all warnings being treated as errors
make: *** [hexdump] Error 1
```

**Comment by wahern** [comment]
That looks like a spurious warning because _fmt is never accessed after any longjump, nor is fmt for that matter. I get the same error message for the src parameter of hxd_write, but it's also spurious.

It appears that only GCC 4.8 has this problem. Not earlier or later versions.

Three alternatives:

1) Use the volatile qualifier. But it would unnecessarily make the code very slow.
2) Move the bulk of hxd_compile and hxd_write into hxd_compile_ and hxd_write_, keeping only the setjmp and error handling code in the original functions.
3) Using pragma to disable -Wclobbered for GCC 4.8. Neither GCC 4.6, 4.7, nor 4.9 complain about the code. And clang doesn't have trouble, either.

My preference is #3, although #2 is also appealing. I'll sleep on it :)
